# Generated by Django 3.0.6 on 2022-12-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20221215_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='images',
            field=models.ImageField(upload_to='catalogo/photos/products'),
        ),
    ]
