# Generated by Django 3.0.6 on 2022-12-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20221215_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='slug',
            new_name='producto_slug',
        ),
    ]
