# Generated by Django 3.0.6 on 2024-07-12 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrito_id', models.CharField(blank=True, max_length=250)),
                ('fecha_agregado', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.Carrito')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Producto')),
            ],
        ),
    ]
