# Generated by Django 3.0.6 on 2022-12-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentas',
            options={'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
    ]
